### ISSUE TITLE
missing word on titan screen

### ISSUE THREAD

**Issue by kreezxil** [FreddecGames/ngspacecompany#43]
![image](https://user-images.githubusercontent.com/3880072/142745180-d1a8acdc-ccf4-4df0-91cc-f01c514a1f77.png)

**Comment by kreezxil** [comment]
well now that I'm reading it again

**maybe rewrite the entire line**

### The Overlord has granted you one and only one opportunity to change the Titan you chose if the need arises as a demonstration of good faith.

**Comment by FreddecGames** [comment]
Fixed in 1.37.0
